Add buddy allocator
secs-dev/xv6-riscv pull request #28
Opened 2024-10-28 15:54 UTC by DecafMangoITMO

2024-10-28 16:20 UTC, e1turin requested changes

2024-10-28 16:20 UTC, e1turin commented on kernel/defs.h
> +};
Может быть можно оставить в `defs.h` только `struct list`, как в начале файла, а реализацию положить в другой файл. Не помню какие проблемы от этого могут возникнуть.

2024-10-28 16:20 UTC, e1turin commented on kernel/defs.h
> +int lst_empty(struct list*);
Добавь, пожалуйста, форматирование для соответствия общему код-стайлу файла

2024-10-28 16:26 UTC, DecafMangoITMO commented on kernel/defs.h
> +};
Такой стиль я взял на основе других заголовочных файлов. Скорее всего, проблем не должно возникнуть.

2024-10-28 16:53 UTC, vityaman commented on kernel/defs.h
> +};
А прагмы ванс нет, потому давайте только декларацию.

2024-10-28 19:14 UTC, vityaman requested changes

2024-10-28 19:14 UTC, vityaman commented on .idea/vcs.xml
Эти файлы следует удалить.

2024-10-28 19:14 UTC, vityaman commented on kernel/defs.h
Давай вообще уберем упоминание листа из defs.h и поместим все объявления в list.h.

2024-10-28 19:16 UTC, DecafMangoITMO commented on .idea/vcs.xml
согласен

2024-10-28 19:23 UTC, vityaman requested changes

2024-10-28 19:23 UTC, vityaman commented on kernel/list.c
> +#include "list.h"
Давай лист будет первой строчкой, а остальные инклюды за ним через строчку. Типа

```
#include "list.h"

#include ...
#include ...
```

2024-10-29 07:29 UTC, e1turin approved these changes

2024-10-29 11:18 UTC, merged